name: PyPI upload
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.71.3
          locked: true
      - run: pixi run build
      - run: pixi run twine check dist/*
      - run: pixi run twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: '${{ secrets.PYPI_API_TOKEN }}'
